spring.application.name=restful-web-services
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb;NON_KEYWORDS=USER
#spring.data.jpa.repositories.bootstrap-mode=default
#spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.security.user.name=mkpoutoe
spring.security.user.password=12345


